version: '3'
services:
  nginx:
   build: .
   restart: unless-stopped
   container_name: nginx
   ports:
     - "80:80"
   volumes:
     - ./data/conf.d:/etc/nginx/conf.d
     - ../robinhood/www:/data/www/robinhood
